### ISSUE TITLE
Error: 'pghi_findgamma' when executing "recover_phase_from_mags.m" with Octave

### ISSUE THREAD

**Issue by SheldonTsui** [tifgan/stftGAN#5]
When I want to recover the phase from the generated magnitudes, Octave can't execute "gamma = pghi_findgamma(win,a,M,Ltrue)" (line 25) successfully in the "recover_phase_from_mags.m". I have installed LTFAT as your requirements. Could you help me?
By the way, have you finished the full-Python implementation of phase recovery?

**Comment by andimarafioti** [comment]
Hey! I finished the full-python implementation. Functions are here: https://github.com/tifgan/stftGAN/tree/master/phase_recovery 
There are two implementations, one uses numba to accelerate greatly the processing, on my laptop it takes +/- 7ms per second of audio. The pure python one we left because we find it easier to understand. The C implementation that matlab uses is still faster, but I think this is good enough for now. There is also a notebook comparing and using them here: https://github.com/tifgan/stftGAN/blob/master/data/pghi%20test.ipynb . 

Regarding your problem with pghi_findgamma, The function belongs to the phase_rec toolbox from ltfat, which you can find here: http://ltfat.github.io/phaseret/ . On the python implementation I don't think we use the toolbox, so if you install ltfatpy you should be all set.

Please let me know if you have any further problems! I will adapt the readme to try to prevent others from having this issue with the toolbox, but having the python implementations we might just remove the matlab code to have a more consistent environment.

**Comment by SheldonTsui** [comment]
Thanks for your response. It really helps me a lot.
Moreover, I still have some questions.

First, What's the difference between "recover_phase_from_mags.m" and "recover_phase_from_mags_and_derivs.m"?

Second, Octave can't execute "c_amp_pghi = pghi(c_amp,gamma,a,M,mask,flag)" (line 37) in the "recover_phase_from_mags.m". Is there another toolbox I should install from [http://ltfat.github.io](url)? Could you kindly add more details in the README.md?

Finally, What's the meaning of 'tgard' and 'fgrad' arguments in the phase_recovery/pghi.py? Since we can only obtain magnitudes from TiFGAN-M model, I am a little confused here.

**Comment by andimarafioti** [comment]
If you read our paper carefully (https://arxiv.org/pdf/1902.04072.pdf), you will notice that we actually tested two approaches to generating the sound signals. The best performing one turned out to be generating the magnitude spectrograms only (TiFGAN-M), but we also tested generating the magnitude spectrograms and the two phase derivatives (time-gradient (tgrad) and frequency-gradient (fgrad)). On the website, the network producing these three is referred to as TiFGAN-MTF (https://tifgan.github.io). The difference between "recover_phase_from_mags.m" and "recover_phase_from_mags_and_derivs.m" is that the first one assumes you only generated magnitudes and the second one assumes you generated magnitude and phase derivatives.

I'm not too sure what to say about the second question. You have the phase recovery toolbox? You initialized both toolboxes? (I think: ltfatstart(); phaseretstart();). If you could upload the traceback maybe I can give you more guidance. I can't add more details to the readme today, but I will make sure to do that as soon as possible. In any case, we can troubleshoot your problems together and then I will also have a better idea of what to write in the readme.

**Comment by SheldonTsui** [comment]
Thank you very much for your kind and patient explanation. I did skip some parts when reading paper. It's really my fault. I have read the paper carefully.

I am so sorry to bother you again. But, what I want to ask in the previous comment is which python script I should use to recover phase from ONLY magnitudes, since we can get only magnitudes from TiFGAN-M model. “pghi.py”? If so, what value should be taken for 'tgrad' and 'fgrad' arguments under this circumstance?

**Comment by andimarafioti** [comment]
No problem. 
To recover the phase from ONLY magnitudes, you can either use "recover_phase_from_mags.m", or you can use 'pghi.py' or 'numba_pghi.py' (This last one just uses numba to accelerate the computation, but the results are equal). To use pghi, you need to have 'tgrad' and 'fgrad'. To obtain them, you can run this:

```python
import ltfatpy
from modGabPhaseGrad import modgabphasegrad
ltfatpy.gabphasegrad = modgabphasegrad 

fft_window_length = 512
fft_hop_size = 128
gs = {'name': 'gauss', 'M': fft_window_length}
tgrad, fgrad = ltfatpy.gabphasegrad('abs', generatedMagnitudes, gs, fft_hop_size)
```

You will find 'modgabphasegrad' here: https://github.com/tifgan/stftGAN/blob/master/data/modGabPhaseGrad.py . We needed to modify ltfatpy's gabphasegrad to add support for the kind of STFT we wanted to use, but the matlab version already supports it.

I see how this pipeline can be a bit confusing. I hope that the notebook that I linked to before (https://github.com/tifgan/stftGAN/blob/master/data/pghi%20test.ipynb) would help more, but I think it still is a bit too messy. I'll work in having a more stream-lined implementation. Thank you for still trying to make it work! And obviously, let me know if I can help you more!

**Comment by SheldonTsui** [comment]
Thanks for your reply. Where is the code part for the consistency \rho of the STFT?

**Comment by andimarafioti** [comment]
Hey Sheldon, sorry for the delay! That one is kind of tricky to find: https://github.com/tifgan/stftGAN/blob/025da3c8bae2bb9b8a2428a77e67a7f0ace1033e/gantools/model.py#L334 
Hope it helps! How did you do why the way? I'm going to adapt the readme today

**Comment by andimarafioti** [comment]
I already adapted the readme to use only the python implementation of the phase recovery, this should solve the original problems presented on this issue.
SheldonTsui, please do still comment if you have further problems!
